import { vuePlugin, vueDefines, sharedStyles } from './ui-package.mjs';
import { build } from 'esbuild';
import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { styles } from '../src/panel.js';
import { panelMessages } from '../src/messages.js';
const root = fileURLToPath(new URL('..', import.meta.url));
const base = fileURLToPath(new URL('../../..', import.meta.url));
const gateway = process.env.CREATIVE_GATEWAY_URL || 'https://getminds.ai/integrations/creative';
const url = new URL(gateway);
if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash) throw new Error('Set a public HTTPS gateway URL');
const translations = Object.fromEntries(Object.values(panelMessages).map(({ id, defaultMessage, description }) => [id, { defaultMessage, description }]));
const define = { ...vueDefines, CREATIVE_GATEWAY_URL: JSON.stringify(gateway) };
let css = styles;
const html = script => `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minds creative review</title><style>${css}</style><main></main>${script}</html>`;
await mkdir(`${root}/dist`, { recursive: true });
await build({ entryPoints: [`${root}/src/canva.ts`], outfile: `${root}/dist/canva/app.js`, bundle: true, format: 'iife', target: 'es2022', plugins: [vuePlugin], define });
await writeFile(`${root}/dist/canva/messages_en.json`, JSON.stringify(translations, null, 2));
await build({ entryPoints: [`${root}/src/figma-main.ts`], outfile: `${root}/dist/figma/code.js`, bundle: true, format: 'iife', target: 'es2022' });
const ui = await build({ entryPoints: [`${root}/src/figma-ui.js`], bundle: true, format: 'iife', target: 'es2022', plugins: [vuePlugin], define, write: false });
css = await sharedStyles(styles);
await writeFile(`${root}/dist/canva/style.css`, css);
const canvaScript = await readFile(`${root}/dist/canva/app.js`, 'utf8');
await writeFile(`${root}/dist/canva/app.js`, `(() => { const style=document.createElement('style');style.textContent=${JSON.stringify(css)};document.head.append(style); })();\n${canvaScript}`);
const legacyCss = css;
css = await sharedStyles('body{padding:16px;font-size:14px}main{max-width:640px;margin:auto}');
await writeFile(`${root}/dist/figma/ui.html`, html(`<script>${ui.outputFiles[0].text.replaceAll('</script', '<\\/script')}</script>`));
css = legacyCss;
const manifest = JSON.parse(await readFile(`${base}/apps/figma/manifest.json`, 'utf8'));
manifest.networkAccess.allowedDomains = [url.origin];
await writeFile(`${root}/dist/figma/manifest.json`, JSON.stringify(manifest, null, 2));
await build({ entryPoints: [`${root}/src/express.js`], outfile: `${root}/dist/express/app.js`, bundle: true, format: 'esm', target: 'es2022', plugins: [vuePlugin], define, external: ['https://express.adobe.com/*'] });
await writeFile(`${root}/dist/express/index.html`, html('<script type="module" src="app.js"></script>'));
await cp(`${base}/apps/adobe-express/manifest.json`, `${root}/dist/express/manifest.json`);
await build({ entryPoints: [`${root}/src/genstudio.ts`], outfile: `${root}/dist/genstudio/app.js`, bundle: true, format: 'esm', target: 'es2022', plugins: [vuePlugin], define });
await writeFile(`${root}/dist/genstudio/index.html`, html('<script type="module" src="app.js"></script>'));
console.log('Built Canva, Figma, Adobe Express and GenStudio development bundles. Gateway deployment is required before host testing.');
