import { build } from 'esbuild';
import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { styles } from '../src/panel.js';
const root = fileURLToPath(new URL('..', import.meta.url));
const base = fileURLToPath(new URL('../../..', import.meta.url));
const gateway = process.env.CREATIVE_GATEWAY_URL || 'https://getminds.ai/integrations/creative';
const url = new URL(gateway);
if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash) throw new Error('Set a public HTTPS gateway URL');
const define = { CREATIVE_GATEWAY_URL: JSON.stringify(gateway) };
const html = script => `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minds creative review</title><style>${styles}</style><main></main>${script}</html>`;
await mkdir(`${root}/dist`, { recursive: true });
await build({ entryPoints: [`${root}/src/canva.ts`], outfile: `${root}/dist/canva/app.js`, bundle: true, format: 'iife', target: 'es2022', define });
await build({ entryPoints: [`${root}/src/figma-main.ts`], outfile: `${root}/dist/figma/code.js`, bundle: true, format: 'iife', target: 'es2022' });
const ui = await build({ entryPoints: [`${root}/src/figma-ui.js`], bundle: true, format: 'iife', target: 'es2022', define, write: false });
await writeFile(`${root}/dist/figma/ui.html`, html(`<script>${ui.outputFiles[0].text.replaceAll('</script', '<\\/script')}</script>`));
const manifest = JSON.parse(await readFile(`${base}/apps/figma/manifest.json`, 'utf8'));
manifest.networkAccess.allowedDomains = [url.origin];
await writeFile(`${root}/dist/figma/manifest.json`, JSON.stringify(manifest, null, 2));
await build({ entryPoints: [`${root}/src/express.js`], outfile: `${root}/dist/express/app.js`, bundle: true, format: 'esm', target: 'es2022', define, external: ['https://express.adobe.com/*'] });
await writeFile(`${root}/dist/express/index.html`, html('<script type="module" src="app.js"></script>'));
await cp(`${base}/apps/adobe-express/manifest.json`, `${root}/dist/express/manifest.json`);
await build({ entryPoints: [`${root}/src/genstudio.ts`], outfile: `${root}/dist/genstudio/app.js`, bundle: true, format: 'esm', target: 'es2022', define });
await writeFile(`${root}/dist/genstudio/index.html`, html('<script type="module" src="app.js"></script>'));
console.log('Built Canva, Figma, Adobe Express and GenStudio development bundles. Gateway deployment is required before host testing.');
